### ISSUE TITLE
Bugs on Business Particulars Header Page

### ISSUE THREAD

**Issue by florentianayuwono** [florentianayuwono/DigitalIT#15]
On recent merge from PR #14, I noticed that there is a bug on the routing/header. After clicking on the View Business Data, we will be directed to the Display/Input Business Particular, but the page has the Logged Out Header. Hence when we go back we will be automatically logged out from the session.

![Screenshot (376)](https://user-images.githubusercontent.com/76247368/175506548-ad33cdbb-f885-410b-b554-2138c642e139.png)

The correct header is supposed to be the Logged In Header like this:

![Screenshot (377)](https://user-images.githubusercontent.com/76247368/175506915-278d5340-e405-4056-8f36-6d4ff0d18fd7.png)

**Comment by KamiliArsyad** [comment]
Alright I'll fix this along with other changes. I think it's because the authentication state is not properly stored in the localstorage. I've also mentioned this problem as a code comment in `authServices.js` file haha

**Comment by florentianayuwono** [comment]
Also, I notice that we have not changed the link for the landing page condition. So the first time the user click on our website link, it should have already been directed to the /landing page. But currently it is still in the / page, and after clicking the Home it then be directed to the /landing.
