### ISSUE TITLE
Returning * when inserting new data

### ISSUE THREAD

**Issue by florentianayuwono** [florentianayuwono/DigitalIT#29]
While reviewing the code, I noticed this code:

`  // check this returning * thing later because this might get very slow if we have to return everything`
` const newUser = await pool.query(
    "INSERT INTO user_account (full_name, email, password, phone_number, creation_date) VALUES ($1, $2, $3, $4, $5) RETURNING *",
    [fullName, email, hashedPass, phoneNumber, getDate()]
  );`
  
  And this RETURNING * line also appears in other controllers. Iirc RETURNING * only returns the inserted content right? Is it necessary or is there any improvement we can do (for example, only return the necessary data points or nothing at all)

**Comment by KamiliArsyad** [comment]
I just read the documentation and yeah everything seems to be correct already since the `RETURNING *` clause actually only returns the modified parts. 
So yup we don't need to change anything and that comment can be deleted.
