### ISSUE TITLE
Reorganizing files and directories

### ISSUE THREAD

**Issue by florentianayuwono** [florentianayuwono/DigitalIT#5]
As of now, our directories and files are kind of in a mess. There are double files for package.json, package-lock.json, app.js, .gitignore and perhaps many others as well. Is there a way to safely combine both files into one file only located in root directory?

I notice that there is a progress ongoing about the React and JWT authentication stuff, and I also plan on integrating the frontend project with PERN and JWT, so perhaps I am going to mess around in a branch after merging the current authentication branch to main.

I plan to reorganize our files to look like a combination of these two: https://github.com/bradtraversy/mern-tutorial and https://github.com/ousecTic/pern-jwt-tutorial

But in order to do this, we must finish all the current progress first and hold for a moment while I reorganize and kind of combine everything. What do you think?

**Comment by KamiliArsyad** [comment]
#6 
Done here ^
