### ISSUE TITLE
Testing to [POST] user data in postman

### ISSUE THREAD

**Issue by florentianayuwono** [florentianayuwono/DigitalIT#7]
In the **react-dev** branch, I am currently trying to match the required user fields with our design and test it out using postman. It seems to work when I deliberately enter uncompleted data, because it returns `"Please complete all required fields."` message. However when I deliberately enter complete data such as this:
```
{
    "fullName": "floren yu",
    "email": "floren@gmail.com",
    "password": "floren123",
    "phoneNumber": "84323"
}
```

, it returns:

```
{
    "message": "The server does not support SSL connections",
    "stack": "Error: The server does not support SSL connections\n    at Socket.<anonymous> (C:\\Users\\HEWLETT PACKARD\\DigitalIT\\node_modules\\pg\\lib\\connection.js:71:37)\n    at Object.onceWrapper (node:events:642:26)\n    at Socket.emit (node:events:527:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
}
```

I actually don't really know whether the postman is connected to my local postgresql database or not. I have created the database in my local machine, but not sure how to check whether it is connected to the code. 

I have tried googling the problem, but also not sure how to interpret them :"(

[similar github issue i guess (?)](https://github.com/developmentseed/osm-teams/issues/136)
[stackoverflow post](https://stackoverflow.com/questions/70857834/error-the-server-does-not-support-ssl-connections)

**Comment by florentianayuwono** [comment]
Also, I notice this when checking the `.env` file. Is this supposed to link to some database that has been created earlier? If so, how can I access it from my local machine?

```
NODE_ENV = development
PORT = 5000
dbHost = ec2-34-227-120-79.compute-1.amazonaws.com
dbUser = sekyknraulqasu
dbPass = dfb8e52ee291f606fa069e87a143d78c03d190dd6df8b83b733d17c82fdc4ab7
database = d76bv03rij1eu8
dbPort = 5432
DATABASE_URL = postgres://sekyknraulqasu:dfb8e52ee291f606fa069e87a143d78c03d190dd6df8b83b733d17c82fdc4ab7@ec2-34-227-120-79.compute-1.amazonaws.com:5432/d76bv03rij1eu8 
```

**Comment by KamiliArsyad** [comment]
Assuming the database and the tables are already created in your local computer, if you want the server to connect to that database instead, you can change the dbHost, dbUser, ... , up till dbPort in the `.env` file to your local db credentials. 
Then in `./backend/config/**db.js**`, uncomment the part where those variables are used and comment the part where the `database_url` is used.
Those steps should change the path to the pool created. Lmk if the error still persists

**Comment by KamiliArsyad** [comment]
Oh also I forgot that the fields for the user registration has not yet been changed because it requires us to reset the db and also re-create the tables. For now the fields for registering a user are email, password, first_name, last_name, and birthdate.
